[build]
  command = "node build.js"
  publish = "_site"

[[redirects]]
  from = "/store"
  to   = "/store.html"
  status = 200

[[redirects]]
  from = "/start-here"
  to   = "/programs.html"
  status = 301

[[redirects]]
  from = "/start-here.html"
  to   = "/programs.html"
  status = 301
